### PR TITLE
first stab at generating new classes based on available additional units

### PR DESCRIPTION
**Pull request by mariannefeng**
Hello, love the project! 

Recently I had a need for being able to set additional units. I liked one of the ideas proposed here:  https://github.com/jmaczan/bulma-helpers/issues/10. 

The default unit for spacing is still pixels, but if additional units are configured via the variable `$additional-spacing-units`, the library would also generate new spacing classes with the configured unit/units. I'm not super familiar with sass, any and all recommendations are welcome. 

Let me know what you think. Once we have an approved solution, I'd be happy to update the README as well.

### CODE REVIEW

**Comment by jmaczan** [comment]
Hello,

Sound good to me. 🙂 As far as I understand, it won't add any classes to bundle by default and it will generate new classes only when you pass values to `$additional-units` array - am I right?

Best,
Jędrzej

**Comment by mariannefeng** [comment]
yep! As-is, there will be no additional classes added to the bundle by default, but if `$additional-units` is overridden by the user, for example, set to `'rem' 'em'`, two new sets of spacing helpers will be generated ending in `-rem` and `-em`

**Comment by jmaczan** [comment]
Okay, cool. You can add README to this pull request and once I revied it, we can merge it to master and release version `0.3.11` :)

**Comment by mariannefeng** [comment]
Updated, ready for review!

**Comment by jmaczan** [comment]
Looks good to me 👍 🙂 Thanks for your contribution, I'll release in few minutes. Good job Marianne!

**Comment by jmaczan** [comment]
Released in 0.3.11, available on npm

**Comment by jmaczan** [comment]
https://www.npmjs.com/package/bulma-helpers

**Pull request merged**
